services:
  - type: web
    name: pdf-resizer-backend
    runtime: docker
    region: frankfurt    # Geringe Latenz für Nutzer in Europa
    plan: free
    envVars:
      - key: PORT
        value: 8080      # Teilt Flask/Gunicorn mit, auf welchem Port es lauschen soll
